### ISSUE TITLE
Note that RED/in-band FEC won't recover header extensions

### ISSUE THREAD

**Issue by juberti** [juberti/draughts#48]
1. Usage of RED and in band FEC and header extensions in Sections 3.2, 3.3 and 4

I think it would be worth noting that neither red/audio nor in-band fec allows to recover RTP header extensions from previous packets. The impact of loosing the header extensions will be dependent of its meaning as, for example, this would cause minor problems to SFUs as client to mixer audio level info of previous packets will be lost, but could make it unusable for PERC (as it is currently defined) as it requires the OHB header extension.

**Comment by murillo128** [comment]
Regarding the issue OHB header usage, it is a required mechanism for PERC double  encryption:

https://tools.ietf.org/html/draft-ietf-perc-double-03

When double encryption is used on a conferencing scenario, SRTP encryption is applied twice, the inner one being end-2-end and the outer one hoop-by-hoop. That allows the SFU to only be involved on the HBH encryption, but pass encrypted media E2E between the participants of the conference for enhanced privacy/security.

This impose that the endpoints are able to reconstruct the original rtp packet before applying the inner crytpo. If RTP headers are lost, then the endpoint will not be able to do so, and will not be able to decrypt the payload.

There is a lot of ongoing discussion regarding FEC/RTX/RED usage within PERC, so I hope to be able to address this issue there (IMHO the current model could be improved by not sending the OHB as header extension but as part of the payload, but that's another topic for discussion). 

So, doing a recap, I don't feel that there is any issues with using RED for audio (the lost of the client to mixer data could cause minor glitches, but I don't feel they would be even noticeable by the end users), but I also feel that it would be good to state what is the current behavior so everyone is aware of what is the expected behavior and may be a key point when moving from RED/audio to Flex FEC in the future if we need to protect any important RTP header extension also.

I can provide a tentative text if you feel so.

**Comment by juberti** [comment]
From email discussion: 

> Maybe it will be good in section 3 to add a section that mention that FEC will protect the whole RTP packet while RED and in-band fec will only protect the RTP payload.
